import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Layout } from '../src/components/layout';
import { getSortedPostsData } from '../src/lib/post';
import { PostMeta } from '../src/type/post';

const Home: NextPage<{ posts: PostMeta[] }> = ({ posts }) => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-4xl text-center">Blog of Melvyn</h1>
        <div>
          {posts.map(({ id, title, description }) => (
            <Link href={`/post/${id}`} key={id}>
              <a className="my-4 block">
                <p className="text-xl font-bold">{title}</p>
                <p>{description}</p>
              </a>
            </Link>
          ))}
        </div>
      </div>
    </Layout>
  );
};

export const getStaticProps = async () => {
  const posts = getSortedPostsData();

  return {
    props: {
      posts,
    },
  };
};

export default Home;
